server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;

    # geoip.dat / geosite.dat — отдаём как бинарь
    location / {
        autoindex on;
        default_type application/octet-stream;
        add_header Cache-Control "public, max-age=3600";
        add_header X-Geo-Serve "1";
    }

    location = /healthz {
        default_type text/plain;
        return 200 "ok\n";
    }
}
